name: Build bun

on:
  push:
      branches: [ "master" ]
  workflow_dispatch:
  pull_request:
    branches: [ "master" ]
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: courses-frontend
        run: npm ci

      - name: Build project
        working-directory: courses-frontend
        run: npm run build
