name: Build bun

on:
  push:
      branches: [ "master" ]
  workflow_dispatch:
  pull_request:
    branches: [ "master" ]
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: courses-frontend
        run: bun install

      - name: Build project
        working-directory: courses-frontend
        run: bun run build
